In [1]:
import pandas as pd 
import numpy as np

In [ ]:
climate_df = pd.read_csv("../raw_data/climate.csv.gz")
climate_updated = pd.read_csv("../raw_data/climate_update_2026.csv.gz")
processed_climate = pd.read_csv("../processed_data/climate/climate.csv.gz")
forecasting_climate = pd.read_csv("../raw_data/forecasting_climate.csv.gz")
forecastingg_climate_updated = pd.read_csv("../raw_data/forecasting_climate_update_2026.csv.gz")
ocean_climate = pd.read_csv("../raw_data/ocean_climate_oscillations.csv.gz")
ocean_climate_updated = pd.read_csv("../raw_data/ocean_climate_oscillations_update_2026.csv.gz")

In [47]:
ocean_climate_updated.head(2)

   Unnamed: 0        date      enso       iod       pdo  epiweek
0        1722  2026-01-04 -1.348603 -0.762492 -1.301753   202601
1        1723  2026-01-11 -1.224109 -0.816989 -0.880724   202602

In [48]:
climate_df['date'] = pd.to_datetime(climate_df['date'])
climate_updated['date'] = pd.to_datetime(climate_updated['date'])
forecasting_climate['reference_month'] = pd.to_datetime(forecasting_climate['reference_month'], format='mixed')
forecastingg_climate_updated['reference_month'] = pd.to_datetime(forecastingg_climate_updated['reference_month'], format='mixed')
# Find the dates
oldest_date = climate_df['date'].min()
newest_date = climate_df['date'].max()
print(f"Oldest date: {oldest_date}, Newest date: {newest_date}")

oldest_date_updated = climate_updated['date'].min()
newest_date_updated = climate_updated['date'].max()
print(f"Oldest date in updated: {oldest_date_updated}, Newest date in updated: {newest_date_updated}")

oldest_date_forecasting = forecasting_climate['reference_month'].min()
newest_date_forecasting = forecasting_climate['reference_month'].max()
print(f"Oldest date in forecasting: {oldest_date_forecasting}, Newest date in forecasting: {newest_date_forecasting}")

oldest_date_forecasting_updated = forecastingg_climate_updated['reference_month'].min()
newest_date_forecasting_updated = forecastingg_climate_updated['reference_month'].max()
print(f"Oldest date in forecasting updated: {oldest_date_forecasting_updated}, Newest date in forecasting updated: {newest_date_forecasting_updated}")

oldest_date_ocean = ocean_climate['date'].min()
newest_date_ocean = ocean_climate['date'].max()
print(f"Oldest date in ocean climate: {oldest_date_ocean}, Newest date in ocean climate: {newest_date_ocean}")

oldest_date_ocean_updated = ocean_climate_updated['date'].min()
newest_date_ocean_updated = ocean_climate_updated['date'].max()
print(f"Oldest date in ocean climate updated: {oldest_date_ocean_updated}, Newest date in ocean climate updated: {newest_date_ocean_updated}")

Oldest date: 1999-12-26 00:00:00, Newest date: 2026-03-15 00:00:00
Oldest date in updated: 2026-01-04 00:00:00, Newest date in updated: 2026-06-21 00:00:00
Oldest date in forecasting: 2010-01-01 00:00:00, Newest date in forecasting: 2026-03-01 00:00:00
Oldest date in forecasting updated: 2026-01-01 00:00:00, Newest date in forecasting updated: 2026-07-01 00:00:00
Oldest date in ocean climate: 1993-01-03, Newest date in ocean climate: 2026-05-10
Oldest date in ocean climate updated: 2026-01-04, Newest date in ocean climate updated: 2026-06-21

In [11]:
climate_df.columns

Index(['date', 'epiweek', 'geocode', 'temp_min', 'temp_med', 'temp_max',
       'precip_min', 'precip_med', 'precip_max', 'pressure_min',
       'pressure_med', 'pressure_max', 'rel_humid_min', 'rel_humid_med',
       'rel_humid_max', 'thermal_range', 'rainy_days'],
      dtype='object')

In [25]:
forecasting_climate.columns

Index(['geocode', 'reference_month', 'forecast_months_ahead', 'temp_med',
       'umid_med', 'precip_tot'],
      dtype='object')

In [4]:
climate_df.head(3)

,date,epiweek,geocode,temp_min,temp_med,temp_max,precip_min,precip_med,precip_max,pressure_min,pressure_med,pressure_max,rel_humid_min,rel_humid_med,rel_humid_max,thermal_range,rainy_days
0,1999-12-26,199952,2700102,20.225500,25.611700,31.6680,0.0000,0.0218,0.1679,0.953100,0.955200,0.956600,37.954800,67.179900,93.839800,11.442500,1
1,2000-01-02,200001,2700102,21.935329,25.499886,30.4940,0.0132,2.6425,10.4447,0.954014,0.955986,0.957686,44.407771,70.016357,90.559814,8.558671,7
2,2000-01-09,200002,2700102,21.285600,25.022900,30.1371,1.3862,9.1152,23.0169,0.954771,0.956700,0.958186,48.266157,72.211186,92.909529,8.851500,7

In [9]:
climate_updated.head(3)

,date,epiweek,geocode,temp_min,temp_med,temp_max,precip_min,precip_med,precip_max,pressure_min,pressure_med,pressure_max,rel_humid_min,rel_humid_med,rel_humid_max,thermal_range,rainy_days
0,2026-01-04,202601,2700102,23.460786,28.046757,33.572071,0.0005,0.814,3.3727,0.956214,0.958471,0.960329,32.332029,55.341857,76.951614,10.111286,6
1,2026-01-11,202602,2700102,22.071243,27.274929,33.359057,0.0000,0.529,2.2618,0.956271,0.958371,0.960157,32.601357,58.828586,86.279871,11.287814,7
2,2026-01-18,202603,2700102,22.574100,27.896914,34.383571,0.2636,1.403,8.2181,0.954714,0.957114,0.959129,28.183771,54.740943,80.645986,11.809471,4

In [13]:
processed_climate.head(3)

,date,epiweek,geocode,temp_min,temp_med,temp_max,precip_min,precip_med,precip_max,pressure_min,pressure_med,pressure_max,rel_humid_min,rel_humid_med,rel_humid_max,thermal_range,rainy_days
0,1999-12-26,199952,2700102,20.225500,25.611700,31.6680,0.0000,0.0218,0.1679,0.953100,0.955200,0.956600,37.954800,67.179900,93.839800,11.442500,1
1,2000-01-02,200001,2700102,21.935329,25.499886,30.4940,0.0132,2.6425,10.4447,0.954014,0.955986,0.957686,44.407771,70.016357,90.559814,8.558671,7
2,2000-01-09,200002,2700102,21.285600,25.022900,30.1371,1.3862,9.1152,23.0169,0.954771,0.956700,0.958186,48.266157,72.211186,92.909529,8.851500,7

In [35]:
dengue_AC_df = pd.read_csv("../processed_data/dengue/dengue_AC_agg.csv.gz")
chikungunya_AC_df = pd.read_csv("../processed_data/chikungunya/chikungunya_AC_agg.csv.gz")

In [36]:
pd.set_option('display.max_columns', None)
dengue_AC_list = dengue_AC_df.columns.tolist()
chikungunya_AC_list = chikungunya_AC_df.columns.tolist()

In [37]:
if set(dengue_AC_list) == set(chikungunya_AC_list):
    print("The columns in both DataFrames are the same.")

The columns in both DataFrames are the same.

In [34]:
dengue_AC_list

['uf',
 'uf_code',
 'date',
 'epiweek',
 'cases',
 'temp_min_mean',
 'temp_med_mean',
 'temp_max_mean',
 'precip_min_mean',
 'precip_med_mean',
 'precip_max_mean',
 'pressure_min_mean',
 'pressure_med_mean',
 'pressure_max_mean',
 'rel_humid_min_mean',
 'rel_humid_med_mean',
 'rel_humid_max_mean',
 'thermal_range_mean',
 'rainy_days_mean',
 'koppen',
 'biome',
 'enso',
 'iod',
 'pdo',
 'pop',
 'year',
 'train_1',
 'train_2',
 'train_3',
 'train_4',
 'target_1',
 'target_2',
 'target_3',
 'target_4',
 'temp_min_mean_lag4',
 'temp_min_mean_lag8',
 'temp_min_mean_lag12',
 'temp_min_mean_lag16',
 'temp_med_mean_lag4',
 'temp_med_mean_lag8',
 'temp_med_mean_lag12',
 'temp_med_mean_lag16',
 'temp_max_mean_lag4',
 'temp_max_mean_lag8',
 'temp_max_mean_lag12',
 'temp_max_mean_lag16',
 'precip_min_mean_lag4',
 'precip_min_mean_lag8',
 'precip_min_mean_lag12',
 'precip_min_mean_lag16',
 'precip_med_mean_lag4',
 'precip_med_mean_lag8',
 'precip_med_mean_lag12',
 'precip_med_mean_lag16',
 'precip_max_mean_lag4',
 'precip_max_mean_lag8',
 'precip_max_mean_lag12',
 'precip_max_mean_lag16',
 'pressure_min_mean_lag4',
 'pressure_min_mean_lag8',
 'pressure_min_mean_lag12',
 'pressure_min_mean_lag16',
 'pressure_med_mean_lag4',
 'pressure_med_mean_lag8',
 'pressure_med_mean_lag12',
 'pressure_med_mean_lag16',
 'pressure_max_mean_lag4',
 'pressure_max_mean_lag8',
 'pressure_max_mean_lag12',
 'pressure_max_mean_lag16',
 'rel_humid_min_mean_lag4',
 'rel_humid_min_mean_lag8',
 'rel_humid_min_mean_lag12',
 'rel_humid_min_mean_lag16',
 'rel_humid_med_mean_lag4',
 'rel_humid_med_mean_lag8',
 'rel_humid_med_mean_lag12',
 'rel_humid_med_mean_lag16',
 'rel_humid_max_mean_lag4',
 'rel_humid_max_mean_lag8',
 'rel_humid_max_mean_lag12',
 'rel_humid_max_mean_lag16',
 'thermal_range_mean_lag4',
 'thermal_range_mean_lag8',
 'thermal_range_mean_lag12',
 'thermal_range_mean_lag16',
 'rainy_days_mean_lag4',
 'rainy_days_mean_lag8',
 'rainy_days_mean_lag12',
 'rainy_days_mean_lag16',
 'temp_min_mean_mean_3mo',
 'temp_min_mean_mean_6mo',
 'temp_min_mean_mean_9mo',
 'temp_min_mean_mean_12mo',
 'temp_med_mean_mean_3mo',
 'temp_med_mean_mean_6mo',
 'temp_med_mean_mean_9mo',
 'temp_med_mean_mean_12mo',
 'temp_max_mean_mean_3mo',
 'temp_max_mean_mean_6mo',
 'temp_max_mean_mean_9mo',
 'temp_max_mean_mean_12mo',
 'precip_min_mean_mean_3mo',
 'precip_min_mean_mean_6mo',
 'precip_min_mean_mean_9mo',
 'precip_min_mean_mean_12mo',
 'precip_med_mean_mean_3mo',
 'precip_med_mean_mean_6mo',
 'precip_med_mean_mean_9mo',
 'precip_med_mean_mean_12mo',
 'precip_max_mean_mean_3mo',
 'precip_max_mean_mean_6mo',
 'precip_max_mean_mean_9mo',
 'precip_max_mean_mean_12mo',
 'pressure_min_mean_mean_3mo',
 'pressure_min_mean_mean_6mo',
 'pressure_min_mean_mean_9mo',
 'pressure_min_mean_mean_12mo',
 'pressure_med_mean_mean_3mo',
 'pressure_med_mean_mean_6mo',
 'pressure_med_mean_mean_9mo',
 'pressure_med_mean_mean_12mo',
 'pressure_max_mean_mean_3mo',
 'pressure_max_mean_mean_6mo',
 'pressure_max_mean_mean_9mo',
 'pressure_max_mean_mean_12mo',
 'rel_humid_min_mean_mean_3mo',
 'rel_humid_min_mean_mean_6mo',
 'rel_humid_min_mean_mean_9mo',
 'rel_humid_min_mean_mean_12mo',
 'rel_humid_med_mean_mean_3mo',
 'rel_humid_med_mean_mean_6mo',
 'rel_humid_med_mean_mean_9mo',
 'rel_humid_med_mean_mean_12mo',
 'rel_humid_max_mean_mean_3mo',
 'rel_humid_max_mean_mean_6mo',
 'rel_humid_max_mean_mean_9mo',
 'rel_humid_max_mean_mean_12mo',
 'thermal_range_mean_mean_3mo',
 'thermal_range_mean_mean_6mo',
 'thermal_range_mean_mean_9mo',
 'thermal_range_mean_mean_12mo',
 'rainy_days_mean_mean_3mo',
 'rainy_days_mean_mean_6mo',
 'rainy_days_mean_mean_9mo',
 'rainy_days_mean_mean_12mo']